# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-11 18:00
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach_Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=20, null=True, verbose_name='用户名')),
                ('order_sn', models.CharField(max_length=30, verbose_name='订单号')),
                ('coupon_cn', models.CharField(blank=True, max_length=20, null=True, verbose_name='优惠劵号')),
                ('trade_no', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='支付生成的订单号')),
                ('coach_name', models.CharField(max_length=50, verbose_name='教练名称')),
                ('order_status', models.CharField(choices=[('TRADE_SUCCESS', '已支付'), ('TRADE_CLOSED', '已取消'), ('WAIT_BUYER_PAY', '待支付')], default='WAIT_BUYER_PAY', max_length=20, verbose_name='订单状态')),
                ('pay_mount', models.FloatField(default=0.0, verbose_name='支付金额')),
                ('order_mount', models.FloatField(default=0.0, verbose_name='订单金额')),
                ('pay_type', models.CharField(choices=[('wechat', '微信'), ('aplipay', '支付宝')], max_length=10, verbose_name='支付方式')),
                ('course_name', models.CharField(max_length=20, verbose_name='课程名称')),
                ('pay_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='支付时间')),
                ('pay_intage', models.IntegerField(default=0, verbose_name='支付积分')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '教练订单',
                'verbose_name_plural': '教练订单',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belong_course', models.CharField(default='限C1报名', max_length=20, verbose_name='所属课程')),
                ('code', models.CharField(blank=True, default='1805071231', max_length=20, null=True, verbose_name='优惠券码')),
                ('coupon_sn', models.CharField(blank=True, max_length=20, null=True, verbose_name='优惠劵号')),
                ('status', models.CharField(choices=[('used', '已使用'), ('onused', '未使用')], max_length=10, verbose_name='使用状态')),
                ('coupon_mount', models.CharField(default='200', max_length=10, verbose_name='面额')),
                ('end_detail', models.TextField(default='自领取之日起30天有效', verbose_name='截止时间')),
                ('use_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='支付时间')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('active', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Active', verbose_name='活动')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course', verbose_name='课程')),
            ],
            options={
                'verbose_name': '优惠劵',
                'verbose_name_plural': '优惠劵',
            },
        ),
        migrations.CreateModel(
            name='Simulator_Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simulatorName', models.CharField(max_length=20, verbose_name='模拟器名称')),
                ('simulatorCode', models.CharField(max_length=50, verbose_name='模拟器唯一码')),
                ('user_code', models.CharField(max_length=100, verbose_name='用户编号')),
                ('order_sn', models.CharField(max_length=30, verbose_name='订单号')),
                ('trade_no', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='支付生成的订单号')),
                ('address', models.CharField(max_length=100, verbose_name='地址')),
                ('appointment_datetime', models.DateField(verbose_name='预约日期')),
                ('appointment_times', models.CharField(max_length=100, verbose_name='预约时间段')),
                ('order_status', models.CharField(choices=[('success', '成功'), ('cancel', '取消'), ('wait', '待支付')], max_length=10, verbose_name='订单状态')),
                ('pay_mount', models.FloatField(default=0.0, verbose_name='支付全额')),
                ('order_mount', models.FloatField(default=0.0, verbose_name='订单金额')),
                ('pay_type', models.CharField(choices=[('wechat', '微信'), ('aplipay', '支付宝')], max_length=10, verbose_name='支付方式')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('pay_intage', models.IntegerField(default=0, verbose_name='支付积分')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '模拟器订单',
                'verbose_name_plural': '模拟器订单',
            },
        ),
    ]
