# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-14 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tradApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='categry',
            field=models.CharField(blank=True, choices=[('voucher', '抵用劵'), ('active', '活动券')], max_length=20, null=True, verbose_name='优惠券类别'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='isover',
            field=models.CharField(blank=True, choices=[('true', '可叠加'), ('false', '不可叠加')], max_length=20, null=True, verbose_name='是否叠加'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='active',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.Active', verbose_name='活动'),
        ),
    ]
