# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-09 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradApp', '0002_auto_20180509_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(blank=True, default='1805071231', max_length=20, null=True, verbose_name='优惠券码'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_sn',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='优惠劵号'),
        ),
    ]
