# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-16 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradApp', '0002_auto_20180514_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach_orders',
            name='coach_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='教练名称'),
        ),
        migrations.AlterField(
            model_name='coach_orders',
            name='order_mount',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='订单金额'),
        ),
    ]
