# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-23 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradApp', '0003_auto_20180516_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='status',
            field=models.CharField(choices=[('used', '已使用'), ('onused', '未使用'), ('outdate', '已过期')], max_length=10, verbose_name='使用状态'),
        ),
    ]
