# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-04 15:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=100, verbose_name='描述')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='费用名称')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
        ),
        migrations.CreateModel(
            name='Practiceplace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=200, upload_to='practicplace /%Y/%m', verbose_name='封面图')),
                ('detail', models.TextField(verbose_name='Tuobaba承诺')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
        ),
        migrations.RemoveField(
            model_name='courseresource',
            name='course',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
        migrations.RemoveField(
            model_name='video',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.RemoveField(
            model_name='course',
            name='click_nums',
        ),
        migrations.RemoveField(
            model_name='course',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='course',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='course',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='course',
            name='fav_nums',
        ),
        migrations.RemoveField(
            model_name='course',
            name='learn_times',
        ),
        migrations.RemoveField(
            model_name='course',
            name='org',
        ),
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
        migrations.RemoveField(
            model_name='course',
            name='tag',
        ),
        migrations.AddField(
            model_name='course',
            name='cost_new',
            field=models.CharField(blank=True, default='4850', max_length=20, null=True, verbose_name='现价'),
        ),
        migrations.AddField(
            model_name='course',
            name='cost_old',
            field=models.CharField(blank=True, default='5000', max_length=20, null=True, verbose_name='原价'),
        ),
        migrations.AddField(
            model_name='course',
            name='detail1',
            field=models.TextField(default='', verbose_name='费用详情'),
        ),
        migrations.AddField(
            model_name='course',
            name='detail2',
            field=models.TextField(default='', verbose_name='赠送课时'),
        ),
        migrations.DeleteModel(
            name='CourseResource',
        ),
        migrations.DeleteModel(
            name='lesson',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.AddField(
            model_name='cost',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course', verbose_name='相关课程'),
        ),
        migrations.AddField(
            model_name='advantage',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course', verbose_name='课程'),
        ),
    ]
