# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-25 13:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180418_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelNumVerifyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='验证码')),
                ('telnum', models.EmailField(max_length=50, verbose_name='电话号码')),
                ('send_type', models.CharField(choices=[('register', '注册'), ('forget', '忘记密码')], max_length=20)),
                ('status', models.CharField(choices=[('true', '可用'), ('fail', '已过期')], max_length=20)),
                ('send_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '短信验证',
                'verbose_name_plural': '短信验证',
            },
        ),
        migrations.DeleteModel(
            name='EmailVerifyRecord',
        ),
    ]
