# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-26 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180425_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telnumverifyrecord',
            name='telnum',
            field=models.CharField(max_length=50, verbose_name='电话号码'),
        ),
    ]
