# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-08 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180426_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='index',
        ),
        migrations.AddField(
            model_name='banner',
            name='detail',
            field=models.CharField(default='新春活动1', max_length=20, verbose_name='活动描述'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='url',
            field=models.URLField(default='http://192.168.192.136:8000/course/get_coupon/1', verbose_name='访问地址'),
        ),
    ]
